package com.ankideku.domain.model

data class Session(
    val id: SessionId = 0,  // Auto-generated by DB
    val deckId: DeckId,
    val deckName: String,   // Snapshot at session creation
    val prompt: String,
    val state: SessionState,
    val progress: SessionProgress,
    val createdAt: Long,   // Unix timestamp in ms
    val updatedAt: Long,   // Unix timestamp in ms
)

sealed class SessionState(val dbString: String) {
    data object Pending : SessionState("pending")
    data object Running : SessionState("running")
    data object Completed : SessionState("completed")
    data object Incomplete : SessionState("incomplete")  // App closed mid-processing
    data class Failed(val message: String, val exitCode: Int? = null) : SessionState("failed")
    data object Cancelled : SessionState("cancelled")

    val isTerminal: Boolean get() = this is Completed || this is Failed || this is Cancelled || this is Incomplete

    companion object {
        fun fromDbString(value: String, message: String? = null, exitCode: Int? = null): SessionState {
            return when (value) {
                Pending.dbString -> Pending
                Running.dbString -> Running
                Completed.dbString -> Completed
                Incomplete.dbString -> Incomplete
                "failed" -> Failed(message ?: "Unknown error", exitCode)
                Cancelled.dbString -> Cancelled
                else -> Pending
            }
        }
    }
}

data class SessionProgress(
    val processedBatches: Int = 0,
    val totalBatches: Int = 0,
    val suggestionsCount: Int = 0,
    val inputTokens: Int = 0,
    val outputTokens: Int = 0,
    val failedBatches: Int = 0,
) {
    val percentage: Float get() = if (totalBatches > 0) processedBatches.toFloat() / totalBatches else 0f
}
