package com.ankideku.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class Suggestion(
    val id: SuggestionId = 0,  // Auto-generated by DB
    val sessionId: SessionId,
    val noteId: NoteId,
    val modelName: String,  // Note type name, looked up from cached_note
    val originalFields: Map<String, NoteField>,
    val changes: Map<String, String>,
    val reasoning: String,
    val status: SuggestionStatus = SuggestionStatus.Pending,
    val editedChanges: Map<String, String>? = null,
    val createdAt: Long = System.currentTimeMillis(),  // Unix timestamp in ms
    val decidedAt: Long? = null,  // Unix timestamp in ms
    val skippedAt: Long? = null,  // When set, suggestion moves to end of queue
)

@Serializable
enum class SuggestionStatus(val dbString: String) {
    Pending("pending"),
    Accepted("accepted"),
    Rejected("rejected");

    companion object {
        private val byDbString = entries.associateBy { it.dbString }
        fun fromDbString(value: String): SuggestionStatus = byDbString[value] ?: Pending
    }
}
